FROM node:8.16.0-stretch AS texture

ARG USERNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $USERNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $USERNAME

ENV HOME=/home/dev-user
RUN mkdir ${HOME} && chown ${USERNAME}:${GID} ${HOME}
USER ${USERNAME}

ENV PROJECT_FOLDER=/opt/sciencebeam-texture
WORKDIR ${PROJECT_FOLDER}
